### ISSUE TITLE
update R version 

### ISSUE THREAD

**Issue by RenhaoL** [Wytamma/rstudio-hpc#8]
I noticed that the R version in the image is 3.6. I was wondering if there is a quick/easy way to upgrade the R version to 4.1. Thanks in advance.

**Comment by RenhaoL** [comment]
I tried to re-build the image from the rocker/tidyverse:4.3.1, but it doesn't seem to change the R version in R studio, which I found weird. Any comments? Thanks!

**Comment by Wytamma** [comment]
Hey @RenhaoL,

That’s really odd! I’ll also try rebuilding and will let you know how I go.

-W

**Comment by RenhaoL** [comment]
I think I figured it out. It’s all due to I don’t have the root access.
Gladly, the —remote worked for me and using the token. For future
reference, create an account with singularity and do ‘singularity remote
login’ before build would work fine.

Thanks for your help!
Renhao

**Comment by Wytamma** [comment]
Ah that makes sense! I’m glad you figured it out :) I’ll update the image to use 4.3.1 by default.
